### ISSUE TITLE
支持解析 LITE_RUNTIME 模式下的数据

### ISSUE THREAD

**Issue by romanholidaypancakes** [zhuzhu-Top/ParsePb#1]

**Comment by zhuzhu-Top** [comment]
我查了下LITE_RUNTIME ，但是应该格式也是跟原始protobuf一样的，你可以给我一些数据吗，序列化后的和原始的内容

**Comment by zhuzhu-Top** [comment]
![image](https://github.com/zhuzhu-Top/ParsePb/assets/35734511/87621f15-fa37-413a-8212-9281577f85aa)
记过测试，如图是我解析的结果，是可以正常解析的

**Comment by zhuzhu-Top** [comment]
你提供的PB我已经加入到测试代码中，测试通过，请同步最新代码查看
