### ISSUE TITLE
json输出不完全的问题

### ISSUE THREAD

**Issue by HollyZoe** [zhuzhu-Top/ParsePb#3]
[v8.zip](https://github.com/user-attachments/files/16359963/v8.zip)
你好，我刚刚编译了源码并测试这份v8.bin文件解析完成后输出有乱码情况，不知道是解析问题还是json输出问题
调用例子和问题描述如图
![a](https://github.com/user-attachments/assets/e980077e-4672-45de-9003-21b73b902d25)
![b](https://github.com/user-attachments/assets/e41247ec-7df5-47ff-9f7b-e859349c1d25)

**Comment by zhuzhu-Top** [comment]
这个pb是你自己生成的吗? 我用别的工具解析的结果似乎也不太对,
如果有proto文件的话,发出来可以让我更快速的定位到问题

**Comment by HollyZoe** [comment]
这个是从数据库里面提取出来的，但是我知道问题在哪了，我打开文件的时候没传std::ios::binary导致读取格式错误，修改后就正常了，谢谢兄弟啦！




***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuzhu-Top/ParsePb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 下午5:31
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuzhu-Top/ParsePb] json输出不完全的问题 (Issue #3)





 
这个pb是你自己生成的吗? 我用别的工具解析的结果似乎也不太对,
 如果有proto文件的话,发出来可以让我更快速的定位到问题

**Comment by zhuzhu-Top** [comment]
我测试的时候,确实解析完成了,但是中间有很大一部分没解析出来,显示的是原始字节

**Comment by zhuzhu-Top** [comment]
我测试的时候,确实解析完成了,但是中间有很大一部分没解析出来,显示的是原始字节

**Comment by HollyZoe** [comment]
因为中间的那一部分原始字节是plist格式需要再用libplist去解析




***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuzhu-Top/ParsePb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 下午5:44
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuzhu-Top/ParsePb] json输出不完全的问题 (Issue #3)





 
我测试的时候,确实解析完成了,但是中间有很大一部分没解析出来,显示的是原始字节

**Comment by zhuzhu-Top** [comment]
好的,我以为是我的问题
 没有问题的话我就关闭issue了
